version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gsm
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: gsm_back
    container_name: backend-container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  frontend:
    image: gsm_zalar_front
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
